sudo: required

services:
   - docker

before_install:
   - docker build -t rajdockerlearning123/react-app -f Dockerfile.dev .

script:
   - docker run -e CI=true rajdockerlearning123/react-app npm run test 
  